//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Earning_details
    {
        public int ID { get; set; }
        public Nullable<int> emekhaqqi { get; set; }
        public Nullable<int> gunluk_haqq { get; set; }
        public Nullable<int> vergi { get; set; }
        public Nullable<int> hefte_is_gunu { get; set; }
        public Nullable<int> ayliq_is_gunu { get; set; }
        public Nullable<int> Emp_id { get; set; }
    
        public virtual Emp_company Emp_company { get; set; }
    }
}
