//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emp_company()
        {
            this.Earning_details = new HashSet<Earning_details>();
            this.Emp_Adress = new HashSet<Emp_Adress>();
            this.Emp_main = new HashSet<Emp_main>();
            this.Is_ayrintilari = new HashSet<Is_ayrintilari>();
            this.Leaves = new HashSet<Leaf>();
            this.Monthly_Leaves = new HashSet<Monthly_Leaves>();
            this.Payrolls = new HashSet<Payroll>();
        }
    
        public int EMP_ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> muraciet_kod { get; set; }
        public string categoriya { get; set; }
        public Nullable<int> Derece { get; set; }
        public string pers_e_mail { get; set; }
        public string kart_number { get; set; }
        public Nullable<int> department { get; set; }
    
        public virtual Department Department1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Earning_details> Earning_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Adress> Emp_Adress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_main> Emp_main { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Is_ayrintilari> Is_ayrintilari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leaf> Leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Monthly_Leaves> Monthly_Leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payroll> Payrolls { get; set; }
    }
}
