//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Adress
    {
        public int ID { get; set; }
        public Nullable<int> Ev_number { get; set; }
        public string kuce_adi { get; set; }
        public string Seher { get; set; }
        public string Sexsiyyet_num { get; set; }
        public string phone_num { get; set; }
        public string mobil_num { get; set; }
        public string main_seher { get; set; }
        public string main_kuce { get; set; }
        public string main_ev { get; set; }
        public string main_phone { get; set; }
        public Nullable<int> Emp_id { get; set; }
    
        public virtual Emp_company Emp_company { get; set; }
    }
}
