//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Is_ayrintilari
    {
        public int ID { get; set; }
        public string is_vaxti { get; set; }
        public string gorus_tarixi { get; set; }
        public string muqavile_tarixi { get; set; }
        public string artim { get; set; }
        public string sobe { get; set; }
        public string department { get; set; }
        public string vezife { get; set; }
        public string mudur { get; set; }
        public string CV { get; set; }
        public Nullable<int> Emp_id { get; set; }
    
        public virtual Emp_company Emp_company { get; set; }
    }
}
