//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leaf
    {
        public int ID { get; set; }
        public string Ay { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public Nullable<int> date_count { get; set; }
        public Nullable<int> tam_gun { get; set; }
        public Nullable<int> gunun_yarisi { get; set; }
        public Nullable<int> Emp_id { get; set; }
        public string Sebeb { get; set; }
        public Nullable<int> tetil_gunu { get; set; }
    
        public virtual Emp_company Emp_company { get; set; }
    }
}
