//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muraciet1
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Gender { get; set; }
        public string DBT { get; set; }
        public string E_mail { get; set; }
        public string Telefon { get; set; }
        public string Tehsil { get; set; }
        public string Tecrube { get; set; }
        public string Onceki_sirket { get; set; }
        public string Vezife { get; set; }
        public Nullable<int> Emekhaqqi { get; set; }
        public string CV { get; set; }
    }
}
